formatter: md
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

version: '>=0.13.0'

sections:
  hide:
    - providers

sort:
  enabled: true
  by: required

settings:
  hide-empty: true

content: |-
  ## Terraform Module for Cloud Platform Feature

  This respository contains Terraform configuration for deploying a reuseable module.

  ### Usage

  ```hcl
  {{ include "examples/example.tf" }}
  ```

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
