name: Azure Login
description: "Login to Azure using managed identity or service principal creds"
inputs:
  auth_method:
    description: "Auth method: managed-identity|service-principal"
    required: false
    default: managed-identity
  azure_credentials:
    description: "JSON credentials for service principal (when auth_method=creds)"
    required: false
  tenant_id:
    description: "Tenant ID (identity)"
    required: false
  subscription_id:
    description: "Subscription ID (identity)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Azure Login with managed identity
      if: ${{ inputs.auth_method == 'managed-identity' }}
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}
        enable-AzPSSession: true

    - name: Azure Login (service principal creds)
      if: ${{ inputs.auth_method == 'service-principal' }}
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true
