# Generated by Ansible - 2026-01-21T21:14:36Z
# Workflow run: https://github.com/dteenergy/cloud-platform-vm-migration/actions/runs/21223499661

locals {
  test_app_resource_prefix = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev"

  # Load patching schedules from JSON file
  # Each VM will have its own schedule configuration
  patching_schedules = fileexists("${path.module}/vm_patching_schedules.json") ? jsondecode(file("${path.module}/vm_patching_schedules.json")) : {}
  
  # Extract unique maintenance configurations from the schedules
  unique_maintenance_configs = distinct([
    for vm_key, schedule in local.patching_schedules : schedule.maintenance_configuration
  ])
  
  # Create a map of maintenance config name to its settings
  # Take the first VM's settings for each unique maintenance configuration
  maintenance_config_settings = {
    for config_name in local.unique_maintenance_configs : config_name => [
      for vm_key, schedule in local.patching_schedules : schedule
      if schedule.maintenance_configuration == config_name
    ][0]
  }
  
  # Map VMs to their maintenance configurations
  vm_to_maintenance_config = {
    for vm_key, schedule in local.patching_schedules : vm_key => schedule.maintenance_configuration
  }
  
  test_app_vms = {
    vmcuwinwebd01 = {
      vmss_name = "vmss-vmcuwinwebd01"
      vm_name   = "vmcuwinwebd01"
      vm_size   = "Standard_D2s_v5"
      network = {
        nic_name                  = "nic-vmcuwinwebd01-00"
        subnet_id                 = module.primary_network.subnet_ids["main"]
        network_security_group_id = null
        enable_nsg                = false
        nsg_name                  = null
        nsg_rules = {
          "allow-rdp" = {
            priority                   = 1000
            direction                  = "Inbound"
            access                     = "Allow"
            protocol                   = "Tcp"
            source_port_range          = "*"
            destination_port_range     = "3389"
            source_address_prefixes    = ["10.0.0.0/8"]
            destination_address_prefix = "*"
          }
        }
      }
      disk = {
        os = {
          name                 = "vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
          caching              = "ReadWrite"
          size_gb              = 100
          storage_account_type = "Standard_LRS"
          create_option        = "Attach"
          os_type              = "Windows"
        }
        data = {
          "vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc" = {
            lun                       = 0
            caching                   = "None"
            write_accelerator_enabled = false
            resource_id               = "${local.test_app_resource_prefix}/providers/Microsoft.Compute/disks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
            disk_size_gb              = 50
            storage_account_type      = "Standard_LRS"
          }
        }
      }
      vm_resource_id                     = "${local.test_app_resource_prefix}/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01"
      nic_resource_id                    = "${local.test_app_resource_prefix}/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"
      os_disk_resource_id                = "${local.test_app_resource_prefix}/providers/Microsoft.Compute/disks/vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
      user_assigned_identity_resource_id = null
      backup = {
        enable_backup                    = true
        backup_vault_name                = "backup-vault-cu-dev-migration-test"
        backup_vault_resource_group_name = "rg-cu-CorpApps-MigrationTest-Dev"
        backup_vault_policy_name         = "daily-migration-test-vm-backup-policy"
      }
    }
  }

  # test_app_app_gateways = {
  #   int_web = {
  #     application_gateway_name_suffix         = "int-web"
  #     sku_name                                = "WAF_v2"
  #     sku_tier                                = "WAF_v2"
  #     sku_capacity                            = 2
  #     key_vault_name                          = "kv-cu-dev-migration-test"
  #     key_vault_public_network_access_enabled = false
  #     create_private_endpoint                 = true
  #     private_endpoint_subnet_id              = module.primary_network.subnet_ids["main"]
  #     skip_dns_zone_for_pep                   = true
  #     gateway_ip_configuration = {
  #       name      = "appgw-ip-config"
  #       subnet_id = module.primary_network.subnet_ids["app-gateway"]
  #     }
  #     identity_name = "id-appgw-cu-dev-migration-test"
  #     frontend_ip_configurations = [
  #       {
  #         name                          = "frontend-ip-internal"
  #         subnet_id                     = module.primary_network.subnet_ids["app-gateway"]
  #         private_ip_address            = cidrhost(module.primary_app_gateway_ipam.allocated_cidr, 5)
  #         private_ip_address_allocation = "Static"
  #         public_ip_address_id          = null
  #         create_public_ip              = false
  #         public_ip_name                = null
  #         domain_name_label             = null
  #       }
  #     ]
  #     frontend_ports = {
  #       http = {
  #         name = "http_port"
  #         port = 80
  #       },
  #       https = {
  #         name = "https_port"
  #         port = 443
  #       }
  #     }
  #     backend_address_pools = {
  #       default = {
  #         name                  = "backend-pool"
  #         fqdns                 = []
  #         ip_addresses          = []
  #         network_interface_ids = ["${local.test_app_resource_prefix}/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"]
  #       }
  #     }
  #     backend_http_settings = {
  #       default = {
  #         name                                = "http-settings"
  #         cookie_based_affinity               = "Disabled"
  #         path                                = "/"
  #         port                                = 80
  #         protocol                            = "Http"
  #         request_timeout                     = 20
  #         probe_name                          = "http-probe"
  #         pick_host_name_from_backend_address = true
  #       }
  #     }
  #     health_probes = {
  #       http-probe = {
  #         name                                      = "http-probe"
  #         protocol                                  = "Http"
  #         path                                      = "/health"
  #         interval                                  = 30
  #         timeout                                   = 30
  #         unhealthy_threshold                       = 3
  #         pick_host_name_from_backend_http_settings = true
  #       }
  #     }
  #     http_listeners = {
  #       http-listener = {
  #         name                           = "http-listener"
  #         frontend_ip_configuration_name = "frontend-ip-internal"
  #         frontend_port_name             = "http_port"
  #         protocol                       = "Http"
  #         ssl_certificate_name           = null
  #         host_name                      = null
  #       },
  #       https-listener = {
  #         name                           = "https-listener"
  #         frontend_ip_configuration_name = "frontend-ip-internal"
  #         frontend_port_name             = "https_port"
  #         protocol                       = "Https"
  #         ssl_certificate_name           = "test-migration-cert"
  #         host_name                      = "test-migration.internal.dteenergy.com"
  #       }
  #     }
  #     redirect_configurations = {
  #       http-to-https = {
  #         name                 = "http-to-https-redirect"
  #         redirect_type        = "Permanent"
  #         target_listener_name = "https-listener"
  #         target_url           = null
  #         include_path         = true
  #         include_query_string = true
  #       }
  #     }
  #     request_routing_rules = {
  #       http-rule = {
  #         name                        = "http-rule"
  #         rule_type                   = "Basic"
  #         http_listener_name          = "http-listener"
  #         backend_address_pool_name   = null
  #         backend_http_settings_name  = null
  #         redirect_configuration_name = "http-to-https-redirect"
  #         priority                    = 100
  #       },
  #       https-rule = {
  #         name                        = "https-rule"
  #         rule_type                   = "Basic"
  #         http_listener_name          = "https-listener"
  #         backend_address_pool_name   = "backend-pool"
  #         backend_http_settings_name  = "http-settings"
  #         redirect_configuration_name = null
  #         priority                    = 200
  #       }
  #     }
  #     enable_waf = true
  #     waf_configuration = {
  #       firewall_mode            = "Prevention"
  #       rule_set_type            = "OWASP"
  #       rule_set_version         = "3.2"
  #       file_upload_limit_mb     = 100
  #       request_body_check       = true
  #       max_request_body_size_kb = 128
  #       disabled_rule_group      = []
  #       exclusion                = []
  #     }
  #     tags = merge(
  #       local.tags,
  #       { "Application" : "WebTier" }
  #     )
  #   }
  # }
}

module "test_app_vms" {
  source  = "app.terraform.io/DTE-Cloud-Platform/imported-vm-pattern/azurerm"
  version = "1.0.6"

  for_each = local.test_app_vms

  # Required context
  vm_name             = each.value.vm_name
  resource_group_name = "rg-cu-CorpApps-MigrationTest-Dev"
  location            = azurerm_resource_group.primary.location
  vm_size             = each.value.vm_size

  # Network
  network = each.value.network

  # Disk
  disk = each.value.disk

  # OS selection
  vm_os_type = lower(each.value.disk.os.os_type)

  # Optional VMSS anchor if vmss_name provided (imports live in root)
  enable_vmss = each.value.vmss_name != null

  # VMSS name for import anchor
  vmss_name = each.value.vmss_name

  # Backup configuration
  enable_backup                    = each.value.backup.enable_backup
  backup_vault_name                = each.value.backup.backup_vault_name
  backup_vault_resource_group_name = each.value.backup.backup_vault_resource_group_name
  backup_vault_policy_name         = each.value.backup.backup_vault_policy_name

  # Windows Update Manager configuration
  # Enable for ALL Windows VMs - schedule is configured in Azure Update Manager
  enable_periodic_update_assessment = lower(each.value.disk.os.os_type) == "windows" ? true : false

  # Tags
  tags = local.tags
}

# module "test_app_app_gateways" {
#   source  = "app.terraform.io/DTE-Cloud-Platform/app-gateway/azurerm"
#   version = "0.0.1"

#   for_each = local.test_app_app_gateways

#   application_gateway_name_suffix = each.value.application_gateway_name_suffix
#   resource_group_name             = "rg-cu-CorpApps-MigrationTest-Dev"
#   location                        = azurerm_resource_group.primary.location
#   environment                     = var.environment == "Development" ? "Dev" : var.environment

#   sku_name     = each.value.sku_name
#   sku_tier     = each.value.sku_tier
#   sku_capacity = each.value.sku_capacity

#   gateway_ip_configuration   = each.value.gateway_ip_configuration
#   frontend_ip_configurations = each.value.frontend_ip_configurations
#   frontend_ports             = each.value.frontend_ports
#   backend_address_pools      = each.value.backend_address_pools
#   backend_http_settings      = each.value.backend_http_settings
#   health_probes              = each.value.health_probes
#   http_listeners             = each.value.http_listeners
#   redirect_configurations    = try(each.value.redirect_configurations, {})
#   request_routing_rules      = each.value.request_routing_rules

#   identity_name                           = try(each.value.identity_name, null)
#   key_vault_name                          = try(each.value.key_vault_name, null)
#   key_vault_public_network_access_enabled = try(each.value.key_vault_public_network_access_enabled, false)
#   create_private_endpoint                 = try(each.value.create_private_endpoint, true)
#   private_endpoint_subnet_id              = try(each.value.private_endpoint_subnet_id, null)
#   skip_dns_zone_for_pep                   = try(each.value.skip_dns_zone_for_pep, false)

#   enable_waf        = try(each.value.enable_waf, false)
#   waf_configuration = try(each.value.waf_configuration, null)

#   tags = each.value.tags
# }

### MAINTENANCE CONFIGURATIONS FOR VM PATCHING ###

# Create Maintenance Configurations based on JSON schedules
resource "azurerm_maintenance_configuration" "vm_patching" {
  for_each = local.maintenance_config_settings
  
  name                = each.key
  resource_group_name = "rg-cu-CorpApps-MigrationTest-Dev"
  location            = azurerm_resource_group.primary.location
  scope               = "InGuestPatch"
  
  window {
    start_date_time = "2026-01-01 ${each.value.time_of_day}:00"
    duration        = each.value.duration
    time_zone       = "Central Standard Time"
    recur_every     = each.value.frequency == "Weekly" ? "Week ${each.value.day_of_week}" : "Day"
  }
  
  install_patches {
    reboot = each.value.reboot_setting
    
    windows {
      classifications_to_include = ["Critical", "Security", "UpdateRollup", "FeaturePack", "ServicePack", "Definition", "Tools", "Updates"]
    }
  }
  
  tags = merge(
    local.tags,
    {
      Purpose     = "VM Patching"
      Description = each.value.description
    }
  )
}

# Assign VMs to their Maintenance Configurations
resource "azurerm_maintenance_assignment_virtual_machine" "vm_patching" {
  for_each = {
    for vm_key in keys(local.test_app_vms) : vm_key => vm_key
    if lower(local.test_app_vms[vm_key].disk.os.os_type) == "windows" && contains(keys(local.vm_to_maintenance_config), vm_key)
  }
  
  location                     = azurerm_resource_group.primary.location
  maintenance_configuration_id = azurerm_maintenance_configuration.vm_patching[local.vm_to_maintenance_config[each.key]].id
  virtual_machine_id           = module.test_app_vms[each.key].vm_id
  
  depends_on = [
    module.test_app_vms
  ]
}

### IMPORT BLOCKS ###

# Imports for vmcuwinwebd01
import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_windows_virtual_machine.main[0]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_network_interface.main
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_managed_disk.os_disk
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/disks/vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
}


import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_managed_disk.data_disk["vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/disks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_virtual_machine_data_disk_attachment.data_disk_attachment["vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01/dataDisks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_windows_virtual_machine_scale_set.vmss[0]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-vmcuwinwebd01"
}
