# Generated by Ansible - 2026-01-14T16:04:01Z
# Workflow run: https://github.com/dteenergy/cloud-platform-vm-migration/actions/runs/21000865460

locals {
  test_app_resource_prefix = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev"
  test_app_vms = {
    vmcuwinwebd01 = {
      vmss_name = "vmss-vmcuwinwebd01"
      vm_name   = "vmcuwinwebd01"
      vm_size   = "Standard_D2s_v5"
      network = {
        nic_name                  = "nic-vmcuwinwebd01-00"
        subnet_id                 = module.primary_network.subnet_ids["main"]
        network_security_group_id = null
        enable_nsg                = false
        nsg_name                  = null
        nsg_rules = {
          "allow-rdp" = {
            priority                   = 1000
            direction                  = "Inbound"
            access                     = "Allow"
            protocol                   = "Tcp"
            source_port_range          = "*"
            destination_port_range     = "3389"
            source_address_prefixes    = ["10.0.0.0/8"]
            destination_address_prefix = "*"
          }
        }
      }
      disk = {
        os = {
          name                 = "vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
          caching              = "ReadWrite"
          size_gb              = 100
          storage_account_type = "Standard_LRS"
          create_option        = "Attach"
          os_type              = "Windows"
        }
        data = {
          "vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc" = {
            lun                       = 0
            caching                   = "None"
            write_accelerator_enabled = false
            resource_id               = "${local.test_app_resource_prefix}}/providers/Microsoft.Compute/disks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
            disk_size_gb              = 50
            storage_account_type      = "Standard_LRS"
          }
        }
      }
      vm_resource_id                     = "${local.test_app_resource_prefix}}/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01"
      nic_resource_id                    = "${local.test_app_resource_prefix}}/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"
      os_disk_resource_id                = "${local.test_app_resource_prefix}}/providers/Microsoft.Compute/disks/vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
      user_assigned_identity_resource_id = null
      backup = {
        enable_backup                    = true
        backup_vault_name                = "backup-vault-cu-dev-migration-test"
        backup_vault_resource_group_name = "rg-cu-CorpApps-MigrationTest-Dev"
        backup_vault_policy_name         = "daily-migration-test-vm-backup-policy"
      }
    }
  }
  test_app_load_balancers = {
    int_web = {
      load_balancer_name     = "int-web"
      load_balancer_sku      = "Standard"
      load_balancer_sku_tier = "Regional"
      frontend_ip_configurations = [
        {
          name                          = "frontend-ip-internal"
          subnet_id                     = module.primary_network.subnet_ids["main"]
          private_ip_address            = null
          private_ip_address_allocation = "Dynamic"
          public_ip_address_id          = null
          create_public_ip              = false
          public_ip_name                = null
          domain_name_label             = null
        }
      ]
      health_probes = {
        http-probe = {
          name                = "http-probe"
          port                = 80
          protocol            = "Http"
          request_path        = "/health"
          interval_in_seconds = 15
          number_of_probes    = 2
        }
      }
      load_balancer_rules = {
        http-rule = {
          name                           = "http-rule"
          protocol                       = "Tcp"
          frontend_port                  = 80
          backend_port                   = 80
          frontend_ip_configuration_name = "frontend-ip-internal"
          backend_pool_name              = null
          probe_name                     = "http-probe"
          floating_ip_enabled            = false
          tcp_reset_enabled              = true
          idle_timeout_in_minutes        = 4
          load_distribution              = "Default"
          disable_outbound_snat          = false
        }
      }
      network_interface_ids                         = ["${local.test_app_resource_prefix}/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"]
      backend_address_pools                         = {}
      create_availability_set                       = false
      availability_set_name                         = null
      availability_set_platform_fault_domain_count  = 2
      availability_set_platform_update_domain_count = 5
      availability_set_managed                      = false
      tags = merge(
        local.tags,
        { "Application" : "WebTier" }
      )
    }
  }
}

module "test_app_vms" {
  source  = "app.terraform.io/DTE-Cloud-Platform/imported-vm-pattern/azurerm"
  version = "1.1.0-alpha.1"

  for_each = local.test_app_vms

  # Required context
  vm_name             = each.value.vm_name
  resource_group_name = "rg-cu-CorpApps-MigrationTest-Dev"
  location            = azurerm_resource_group.primary.location
  vm_size             = each.value.vm_size

  # Network
  network = each.value.network

  # Disk
  disk = each.value.disk

  # OS selection
  vm_os_type = lower(each.value.disk.os.os_type)

  # Optional VMSS anchor if vmss_name provided (imports live in root)
  enable_vmss = each.value.vmss_name != null

  # VMSS name for import anchor
  vmss_name = each.value.vmss_name

  # Backup configuration
  enable_backup                    = each.value.backup.enable_backup
  backup_vault_name                = each.value.backup.backup_vault_name
  backup_vault_resource_group_name = each.value.backup.backup_vault_resource_group_name
  backup_vault_policy_name         = each.value.backup.backup_vault_policy_name

  # Tags
  tags = local.tags
}

module "test_app_load_balancers" {
  source  = "app.terraform.io/DTE-Cloud-Platform/load-balancer/azurerm"
  version = "1.0.2"

  for_each = local.test_app_load_balancers

  load_balancer_name_suffix = each.value.load_balancer_name
  resource_group_name       = "rg-cu-CorpApps-MigrationTest-Dev"
  location                  = azurerm_resource_group.primary.location
  environment               = var.environment

  load_balancer_sku          = each.value.load_balancer_sku
  load_balancer_sku_tier     = each.value.load_balancer_sku_tier
  frontend_ip_configurations = each.value.frontend_ip_configurations
  health_probes              = each.value.health_probes
  load_balancer_rules        = each.value.load_balancer_rules
  network_interface_ids      = each.value.network_interface_ids

  backend_address_pools                         = try(each.value.backend_address_pools, {})
  create_availability_set                       = try(each.value.create_availability_set, false)
  availability_set_name                         = try(each.value.availability_set_name, null)
  availability_set_platform_fault_domain_count  = try(each.value.availability_set_platform_fault_domain_count, 2)
  availability_set_platform_update_domain_count = try(each.value.availability_set_platform_update_domain_count, 5)
  availability_set_managed                      = try(each.value.availability_set_managed, false)

  tags = try(each.value.tags, {})
}

### IMPORT BLOCKS ###

# Imports for vmcuwinwebd01
import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_windows_virtual_machine.main[0]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_network_interface.main
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Network/networkInterfaces/nic-vmcuwinwebd01-00"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_managed_disk.os_disk
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/disks/vmcuwinwebd01-OSdisk-00-dda752f1-7395-4bcf-ac67-58716e5de28e"
}


import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_managed_disk.data_disk["vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/disks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_virtual_machine_data_disk_attachment.data_disk_attachment["vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachines/vmcuwinwebd01/dataDisks/vmcuwinwebd01-datadisk-01-073cfec7-5b88-491e-8e62-3b6b95371acc"
}

import {
  to = module.test_app_vms["vmcuwinwebd01"].azurerm_windows_virtual_machine_scale_set.vmss[0]
  id = "/subscriptions/6796a2fb-2928-4ec6-96da-962d3b0001b7/resourceGroups/rg-cu-CorpApps-MigrationTest-Dev/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-vmcuwinwebd01"
}
