name: Setup Ansible and Azure SDKs
description: "Install Ansible core, Ansible collections, and Azure SDKs"
inputs:
  ansible_version:
    description: "Version spec for ansible-core"
    required: false
    default: ">=2.15"
  collections_requirements:
    description: "Path to Ansible collections requirements.yml"
    required: false
    default: ansible/requirements.yml
  install_azure_cli:
    description: "Install Azure CLI via pip"
    required: false
    default: "false"
  install_powershell:
    description: "Install PowerShell (pwsh) and Az modules"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Ansible core
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install "ansible-core${{ inputs.ansible_version }}"

    - name: Install Ansible collections
      shell: bash
      run: |
        ansible-galaxy collection install -r ${{ inputs.collections_requirements }}

    - name: Install Azure SDKs for azure.azcollection
      shell: bash
      run: |
        python3 -m pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

    - name: Install Azure CLI (optional)
      if: ${{ inputs.install_azure_cli == 'true' }}
      shell: bash
      run: |
        python3 -m pip install azure-cli

    - name: Install PowerShell (pwsh) on RHEL
      if: ${{ inputs.install_powershell == 'true' && runner.os == 'Linux' }}
      shell: bash
      run: |
        set -euo pipefail
        if [ -f /etc/os-release ]; then
          . /etc/os-release
        else
          echo "/etc/os-release not found" >&2
          exit 1
        fi

        if [ "${ID:-}" != "rhel" ]; then
          echo "This step only supports RHEL (ID=rhel)." >&2
          exit 1
        fi

        if command -v dnf >/dev/null 2>&1; then
          if [ -n "${VERSION_ID:-}" ]; then
            major="${VERSION_ID%%.*}"
          else
            major=""
          fi
          if [ -z "$major" ]; then
            echo "Could not determine RHEL-family major version" >&2
            exit 1
          fi
          sudo dnf install -y "https://packages.microsoft.com/config/rhel/${major}/packages-microsoft-prod.rpm"
          sudo dnf install -y powershell
        elif command -v yum >/dev/null 2>&1; then
          if [ -n "${VERSION_ID:-}" ]; then
            major="${VERSION_ID%%.*}"
          else
            major=""
          fi
          if [ -z "$major" ]; then
            echo "Could not determine RHEL-family major version" >&2
            exit 1
          fi
          sudo yum install -y "https://packages.microsoft.com/config/rhel/${major}/packages-microsoft-prod.rpm"
          sudo yum install -y powershell
        else
          echo "Neither dnf nor yum found; cannot install on RHEL" >&2
          exit 1
        fi

    - name: Install PowerShell (pwsh) on macOS
      if: ${{ inputs.install_powershell == 'true' && runner.os == 'macOS' }}
      shell: bash
      run: |
        brew update
        brew install --cask powershell || true

    - name: Install Az PowerShell modules
      if: ${{ inputs.install_powershell == 'true' }}
      shell: bash
      run: |
        pwsh -NoLogo -NoProfile -NonInteractive -Command "
          \$modules = @(
            'Az.Accounts',
            'Az.Resources',
            'Az.Network',
            'Az.Migrate'
          );
          Install-Module -Name \$modules -Force -Scope CurrentUser -AllowClobber"

    - name: Install pip packaging tools
      shell: bash
      run: |
        python3 -m pip install --upgrade packaging
